<?php 

////////////////////////
///Valores Server
////////////////////////
define ('SITE_ROOT', realpath(dirname(__FILE__) . '/../') );

////////////////////////
///Valores de DB Local
////////////////////////
define('DSN', 'mysql:host=localhost;dbname=vistage;charset=utf8;port:3306');
define('DB_USER', 'root');
define('DB_PASS', 'root');

//////////////////////////////
///Valores de Envio de emails
//////////////////////////////
// define('SMTP', 'smtp.dellabitta.com.ar');
// define('EMAIL_SENDER', 'presupuestos@dellabitta.com.ar');
// define('EMAIL_SENDER_SHOW', 'presupuestos@dellabitta.com.ar');
// define('NAME_SENDER_SHOW', 'Ascensores Dellabitta');
// define('EMAIL_RECIPIENT', 'presupuestos@dellabitta.com.ar');
// define('EMAIL_BCC', 'pablo@librecomunicacion.net');
// define('EMAIL_PASS', 'g4jNAwBwjGA3');
// define('EMAIL_PORT', 587);
// define('EMAIL_NAME', 'Ascensores Dellabitta');
// define('EMAIL_SUBJECT', 'Gracias por tu contacto');
// define('EMAIL_CHARSET', 'utf-8');
// define('EMAIL_ENCODING', 'quoted­printable');


?>